version: '3.7'

services:
  ghost-theme-docker:
    build:
      context: .
    container_name: shedeh
    restart: unless-stopped
    volumes:
      - './data:/var/lib/ghost/content/data'
      - './images:/var/lib/ghost/content/images'
      - './settings:/var/lib/ghost/content/settings'
      - './themes:/var/lib/ghost/content/themes'
      
    ports:
      - "3102:2368"
    environment:
      - NODE_ENV=development
